# Generated by Django 4.2.15 on 2024-08-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userId',
            new_name='user',
        ),
    ]
