# Generated by Django 4.2.15 on 2024-09-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='products_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createdTime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='product_type',
        ),
    ]
