# Generated by Django 4.2.15 on 2024-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Meat'), (2, 'Milk'), (3, 'Ice Cream'), (4, 'Drink'), (5, 'Bread')]),
        ),
    ]
